### ISSUE TITLE
`makepkg -e` runs `prepare()`

### ISSUE THREAD

**Issue by elieux** [Alexpux/MSYS2-pacman#15]
Upstream pacman doesn't run `prepare()` when the `-e` argument is passed. MSYS2 pacman does.

I assume it's because of a this block: [makepkg.sh.in#L2167-L2169](https://github.com/Alexpux/MSYS2-pacman/blob/master/scripts/makepkg.sh.in#L2167-L2169)
```
if (( PREPAREFUNC && !REPKG )); then
	run_prepare
fi
```

Why is it there?

**Comment by Alexpux** [comment]
This tell to not run prepare when you run repackage

**Comment by elieux** [comment]
Can you compare that section of `makepkg.sh.in` with upstream? It's not there at all.

**Comment by DavidEGrayson** [comment]
It looks like https://github.com/Alexpux/MSYS2-pacman/commit/8d1ee78f61b4953227841cedfab0c7a54c988ba5 fixes this.

**Comment by elieux** [comment]
Yeah, I talked to Alexey on IRC and he fixed it. Thanks, Alexey.
