### ISSUE TITLE
Scan for build directory absolute Windows path after building

### ISSUE THREAD

**Issue by DavidEGrayson** [Alexpux/MSYS2-pacman#16]
Several issues reported to the MINGW-packages repository resulted from the Windows path to the packager's MSYS2 installation accidentally being baked into the package itself:

* https://github.com/Alexpux/MINGW-packages/issues/816
* https://github.com/Alexpux/MINGW-packages/issues/775
* https://github.com/Alexpux/MINGW-packages/pull/776
* https://github.com/Alexpux/MINGW-packages/issues/402
* https://github.com/Alexpux/MINGW-packages/issues/381
* https://github.com/Alexpux/MINGW-packages/issues/248

I would suggest adding a pass to makepkg that scans the package for this issue.  Something like this could go a long way:

    grep -Fr `cygpath -w /` $pkgdir && echo "warning: absolute path to build directory found in package"

**Comment by yfwz100** [comment]
I suggest the detection command changed to 
```
grep -Fr `cygpath -m /` $pkgdir && echo "warning: absolute path to build directory found in package"
```

`cygpath -w /` fail to detect path with '/' as separator.

**Comment by DavidEGrayson** [comment]
Thanks, that's a good idea.  I don't know which version is more common (the one with forward slashes or backslashes).  We might as well check for both.

**Comment by DavidEGrayson** [comment]
makepkg already has a feature for warning about build directoyr references:

https://github.com/Alexpux/MSYS2-pacman/blob/master/scripts/libmakepkg/lint_package/build_references.sh.in

I am working on a pull request that improves that script.

**Comment by yfwz100** [comment]
:+1:
