### ISSUE TITLE
Add an option to exit from `update-core`

### ISSUE THREAD

**Issue by techtonik** [Alexpux/MSYS2-pacman#29]
An option to still exit from `update-core` endless loop would be very much appreciated for unattented installs, which are necessary for some "tool-building toolchains". =) https://github.com/mingwpy/mingwpy/pull/19#issuecomment-203234480
I just sent a letter to mailing list and then found this tracker, which seems to be the right place for such request.

**Comment by Alexpux** [comment]
There are no ````update-core```` script anymore.
Read more carefully https://github.com/Alexpux/MSYS2-pacman/pull/26

**Comment by techtonik** [comment]
@Alexpux yes, I've seen that bash script was removed. Thought that the code was just rewritten as C++ program. The option is needed to exit from this loop - https://github.com/Alexpux/MSYS2-pacman/pull/26/files#diff-2ebc1af9d6d7b2b33621d6b763fe8e8bR722

**Comment by Alexpux** [comment]
We not exit this loop to not show fork errors to users.

**Comment by techtonik** [comment]
Looks like `--noconfirm` exits automatically, is that right?

**Comment by Alexpux** [comment]
Yes it seems.

**Comment by Alexpux** [comment]
New pacman in repo now.

**Comment by techtonik** [comment]
Awesome. Are there are rumors when a new MSYS2 version will be released?

**Comment by Alexpux** [comment]
Need fix some issues before release new installers

**Comment by techtonik** [comment]
Any [milestone](https://github.com/Alexpux/MSYS2-pacman/milestones)s to check if anything can be helped to speed up the process?

**Comment by techtonik** [comment]
Actually, I need only .7z archive - no installer is needed.
