### ISSUE TITLE
Installer should create mingw32 and mingw64 directories

### ISSUE THREAD

**Issue by jeroen** [Alexpux/MSYS2-pacman#39]
Started on a fresh machine with the latest msys2 installer. However I run into a conflict that seems to be caused by the fact that the `$(msys2)/mingw64` is now an executable that starts a shell, so the system cannot create the `/mingw64` directory anymore!

<img width="501" alt="installer" src="https://cloud.githubusercontent.com/assets/216319/18794458/ebc8e7e4-81bf-11e6-931c-a6d10668752e.PNG">

**Comment by jeroen** [comment]
I was able to solve the problem by manually creating `/mingw32` and `/mingw64` directories in windows explorer. I couldn't do this from msys2 because it already has those executebles.

**Comment by selay01** [comment]
I was able to solve the problem by manually creating /mingw32 and /mingw64 directories in windows explorer.----------------->i did this too,but why the bash give the confused infomation?!!!!!

**Comment by landfillbaby** [comment]
`mkdir /mingw{32,64}` from the MSYS shell worked for me. The only existing files by those names were the `.exe` and `.ini` ones, but it still got confused.

**Comment by jeroen** [comment]
I think this has been solved. I no longer experience this issue.
