### ISSUE TITLE
Interop failure.

### ISSUE THREAD

**Issue by ci70** [Alexpux/MSYS2-pacman#45]
This works on Bash for Windows fails on MSYS2.

export PATH=$PATH:/mnt/c/Windows/System32
FLAGS=--cache-size=100
setx.exe /m TEST "$FLAGS"

MSYS2 reports ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).
Which is wrong.

**Comment by ci70** [comment]
Correct way is to use -m not /m. Should be mentioned IMHO.

**Comment by elieux** [comment]
1. Not really *the correct way*, it's just a workaround that works for *some* Microsoft tools.

2. Documentation on path mangling (which is taking place here) is [here](https://github.com/msys2/msys2/wiki/How-does-MSYS2-differ-from-Cygwin#runtime) and [here](https://github.com/msys2/msys2/wiki/Porting#user-content-filesystem-namespaces).

3. I presume you didn't change your `/etc/fstab` in which case the first line (with `export PATH=...`) is useless, as `/mnt/c/` doesn't exist (unless you created a symlink, I guess).

4. Why would you assume everything from WSL works verbatim in MSYS2?

**Comment by ci70** [comment]
Thanks, I honestly think MSYS2 is better than WSL. Since I only write WIN apps.
