### ISSUE TITLE
Pacman is removing old MPFR version file.

### ISSUE THREAD

**Issue by hiro2233** [Alexpux/MSYS2-pacman#51]
Hello,

I'm glad to meet you and work with msy2, this is my first issue, i hope this can help to fix some problems.
Sorry if i'm posting the issue without a some rule, if there is one please point me, i will try to do on the correct way.

The issue:

I'm trying to install by hand the mpfr library with this: http://repo.msys2.org/msys/i686/mpfr-devel-4.0.0.1-3-i686.pkg.tar.xz because this one have both mpfr file version 4th and 6th, when update/upgrade with pacman the 4th version is removed, so it's is needed when linking for numpy on python2. Please try to keep it instead about removing.

Thanks.
Hiroshi Takey F.

**Comment by Alexpux** [comment]
@hiro2233 instead keeping many fake dlls need to build packages with current one. I will never leave old file for compatibility, this is wrong way

**Comment by hiro2233** [comment]
@Alexpux ok, surely you must have the reasons to do that. Thank you for your reply.
