### ISSUE TITLE
any plan to keep up Arch Linux's pacman version?

### ISSUE THREAD

**Issue by dlintw** [Alexpux/MSYS2-pacman#55]
Check it, it is 5.1.1 now.
https://git.archlinux.org/pacman.git/tree/NEWS

**Comment by mingwandroid** [comment]
PRs welcome

**Comment by Alexpux** [comment]
We also have 5.1.1

**Comment by mingwandroid** [comment]
Ha ha sorry I didn't check.

**Comment by dlintw** [comment]
I found the tags and release is on 5.0.x but on the 5.1.1 is already on binary repository, any reason to let them inconsistent?

**Comment by Alexpux** [comment]
This repository dont used anymore. I use release sources from Arch Linux and all patches here - https://github.com/Alexpux/MSYS2-packages/tree/master/pacman

**Comment by FrankHB** [comment]
@Alexpux Please archive this repo and update README to make sure issues can be reported at right place. Not all reporters are coming from https://github.com/msys2/msys2 with the rule in mind.
